# Generated by Django 5.0.1 on 2024-01-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='date',
            new_name='timestamp',
        ),
    ]
